version: '3'
services:
  flaskapp:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DISPLAY=:99  # Ensure the environment variable for headless Chrome
    volumes:
      - .:/app
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
